package tmpl

// sprigDocs documents every function contributed by
// github.com/Masterminds/sprig/v3's FuncMap (see
// https://masterminds.github.io/sprig/ for the authoritative reference).
// A handful of names — randInt, randBytes, pick, shuffle, ext — are
// DELIBERATELY OVERRIDDEN by maelsink's own functions later in
// Engine.FuncMap()'s assembly order (see engine.go), so those five keys
// are documented in Docs() itself under maelsink's own semantics, not
// here, and are intentionally absent from this map to avoid describing
// behavior that never actually runs.
func sprigDocs() map[string]FuncDoc {
	return map[string]FuncDoc{
		// String
		"abbrev":       {"abbrev maxWidth s", "Truncates s to maxWidth, appending \"...\" if it was cut."},
		"abbrevboth":   {"abbrevboth left right s", "Like abbrev, but can also truncate the left side."},
		"camelcase":    {"camelcase s", "Converts s to CamelCase."},
		"cat":          {"cat a b ...", "Concatenates its arguments (space-separated) into one string."},
		"contains":     {"contains substr s", "Reports whether s contains substr."},
		"hasPrefix":    {"hasPrefix prefix s", "Reports whether s starts with prefix."},
		"hasSuffix":    {"hasSuffix suffix s", "Reports whether s ends with suffix."},
		"indent":       {"indent spaces s", "Indents every line of s by `spaces` spaces."},
		"initials":     {"initials s", "Returns the initials of each word in s."},
		"kebabcase":    {"kebabcase s", "Converts s to kebab-case."},
		"lower":        {"lower s", "Lowercases s."},
		"nindent":      {"nindent spaces s", "Like indent, but also prepends a newline."},
		"nospace":      {"nospace s", "Removes all whitespace from s."},
		"plural":       {"plural one many n", "Returns `one` if n==1, else `many`."},
		"quote":        {"quote a ...", "Double-quotes and space-joins its arguments."},
		"randAlpha":    {"randAlpha n", "Random string of n letters."},
		"randAlphaNum": {"randAlphaNum n", "Random string of n letters and digits."},
		"randAscii":    {"randAscii n", "Random string of n printable ASCII characters."},
		"randNumeric":  {"randNumeric n", "Random string of n digits."},
		"repeat":       {"repeat count s", "Repeats s count times."},
		"replace":      {"replace old new s", "Replaces every occurrence of old with new in s."},
		"snakecase":    {"snakecase s", "Converts s to snake_case."},
		"squote":       {"squote a ...", "Single-quotes and space-joins its arguments."},
		"substr":       {"substr start end s", "Returns the substring of s from start to end."},
		"swapcase":     {"swapcase s", "Swaps the case of every letter in s."},
		"title":        {"title s", "Title-cases s (capitalizes each word)."},
		"trim":         {"trim s", "Removes leading/trailing whitespace from s."},
		"trimAll":      {"trimAll chars s", "Removes leading/trailing characters in `chars` from s."},
		"trimall":      {"trimall chars s", "Deprecated alias of trimAll."},
		"trimPrefix":   {"trimPrefix prefix s", "Removes prefix from s if present."},
		"trimSuffix":   {"trimSuffix suffix s", "Removes suffix from s if present."},
		"trunc":        {"trunc n s", "Truncates s to n characters (negative n truncates from the left)."},
		"untitle":      {"untitle s", "Removes title-casing from s."},
		"upper":        {"upper s", "Uppercases s."},
		"wrap":         {"wrap width s", "Wraps s onto multiple lines at `width` characters."},
		"wrapWith":     {"wrapWith width sep s", "Like wrap, but uses `sep` as the line-break sequence."},

		// String list
		"join":      {"join sep list", "Joins list's elements with sep."},
		"splitList": {"splitList sep s", "Splits s on sep, returning a list."},
		"split":     {"split sep s", "Splits s on sep, returning a dict of _0, _1, ..."},
		"splitn":    {"splitn sep n s", "Like split, but stops after n substrings."},
		"sortAlpha": {"sortAlpha list", "Sorts a list of strings alphabetically."},

		// Integer math
		"add":     {"add a b ...", "Sums its integer arguments."},
		"add1":    {"add1 a", "Increments a by 1."},
		"sub":     {"sub a b", "a - b."},
		"div":     {"div a b", "Integer division: a / b."},
		"mod":     {"mod a b", "a % b."},
		"mul":     {"mul a b ...", "Multiplies its integer arguments."},
		"max":     {"max a b ...", "The largest of its integer arguments."},
		"min":     {"min a b ...", "The smallest of its integer arguments."},
		"biggest": {"biggest a b ...", "Alias of max."},
		"ceil":    {"ceil a", "Rounds a float up to the nearest integer."},
		"floor":   {"floor a", "Rounds a float down to the nearest integer."},
		"round":   {"round a precision", "Rounds a to `precision` decimal places."},
		"randInt": {"randInt min max", "Random int in [min,max) (sprig's version — shadowed by maelsink's own [min,max]-inclusive randInt; see Docs())."},

		// Float math
		"add1f": {"add1f a", "Float64 version of add1."},
		"addf":  {"addf a b ...", "Float64 version of add."},
		"subf":  {"subf a b ...", "Float64 version of sub."},
		"divf":  {"divf a b ...", "Float64 version of div."},
		"mulf":  {"mulf a b ...", "Float64 version of mul."},
		"maxf":  {"maxf a b ...", "Float64 version of max."},
		"minf":  {"minf a b ...", "Float64 version of min."},

		// Date
		"now":              {"now", "The current time.Time."},
		"ago":              {"ago t", "A human-readable duration since t (e.g. \"3 hours ago\")."},
		"date":             {"date fmt t", "Formats t using a reference-time layout string."},
		"dateInZone":       {"dateInZone fmt t zone", "Like date, in the given IANA time zone."},
		"date_in_zone":     {"date_in_zone fmt t zone", "Deprecated alias of dateInZone."},
		"dateModify":       {"dateModify modifier t", "Applies a Go duration-style modifier (e.g. \"-1.5h\") to t."},
		"date_modify":      {"date_modify modifier t", "Deprecated alias of dateModify."},
		"mustDateModify":   {"mustDateModify modifier t", "Like dateModify, but returns an error instead of the zero value on failure."},
		"must_date_modify": {"must_date_modify modifier t", "Deprecated alias of mustDateModify."},
		"duration":         {"duration seconds", "Formats a number of seconds as a Go duration string."},
		"durationRound":    {"durationRound duration", "Rounds a duration to its largest unit (e.g. \"2h34m\" -> \"3h\")."},
		"htmlDate":         {"htmlDate t", "Formats t as an HTML5 date input value (YYYY-MM-DD)."},
		"htmlDateInZone":   {"htmlDateInZone t zone", "Like htmlDate, in the given IANA time zone."},
		"toDate":           {"toDate fmt s", "Parses s using layout fmt into a time.Time."},
		"mustToDate":       {"mustToDate fmt s", "Like toDate, but returns an error instead of the zero value on failure."},
		"unixEpoch":        {"unixEpoch t", "Returns t as a Unix epoch integer (seconds)."},

		// Defaults
		"default":  {"default fallback value", "Returns value, or fallback if value is empty."},
		"empty":    {"empty value", "Reports whether value is its type's zero value."},
		"coalesce": {"coalesce a b ...", "Returns the first non-empty argument."},
		"ternary":  {"ternary truthy falsy cond", "Returns truthy if cond is true, else falsy."},
		"fail":     {"fail message", "Unconditionally fails template rendering with message."},

		// Encoding
		"b64enc": {"b64enc s", "Base64-encodes s."},
		"b64dec": {"b64dec s", "Base64-decodes s."},
		"b32enc": {"b32enc s", "Base32-encodes s."},
		"b32dec": {"b32dec s", "Base32-decodes s."},

		// Lists
		"list":        {"list a b ...", "Builds a list from its arguments."},
		"append":      {"append list v", "Returns list with v appended."},
		"mustAppend":  {"mustAppend list v", "Like append, but returns an error instead of the zero value on failure."},
		"push":        {"push list v", "Alias of append."},
		"mustPush":    {"mustPush list v", "Alias of mustAppend."},
		"prepend":     {"prepend list v", "Returns list with v prepended."},
		"mustPrepend": {"mustPrepend list v", "Like prepend, but returns an error instead of the zero value on failure."},
		"first":       {"first list", "The first element of list."},
		"mustFirst":   {"mustFirst list", "Like first, but returns an error instead of the zero value on an empty list."},
		"rest":        {"rest list", "All but the first element of list."},
		"mustRest":    {"mustRest list", "Like rest, but returns an error instead of the zero value on an empty list."},
		"last":        {"last list", "The last element of list."},
		"mustLast":    {"mustLast list", "Like last, but returns an error instead of the zero value on an empty list."},
		"initial":     {"initial list", "All but the last element of list."},
		"mustInitial": {"mustInitial list", "Like initial, but returns an error instead of the zero value on an empty list."},
		"reverse":     {"reverse list", "list in reverse order."},
		"mustReverse": {"mustReverse list", "Like reverse, but returns an error instead of the zero value on failure."},
		"uniq":        {"uniq list", "list with duplicate elements removed."},
		"mustUniq":    {"mustUniq list", "Like uniq, but returns an error instead of the zero value on failure."},
		"without":     {"without list a ...", "list with the given elements removed."},
		"mustWithout": {"mustWithout list a ...", "Like without, but returns an error instead of the zero value on failure."},
		"has":         {"has needle list", "Reports whether list contains needle."},
		"mustHas":     {"mustHas needle list", "Like has, but returns an error instead of the zero value on failure."},
		"compact":     {"compact list", "list with empty elements removed."},
		"mustCompact": {"mustCompact list", "Like compact, but returns an error instead of the zero value on failure."},
		"concat":      {"concat list1 list2 ...", "Concatenates lists."},
		"chunk":       {"chunk size list", "Splits list into chunks of at most `size` elements."},
		"mustChunk":   {"mustChunk size list", "Like chunk, but returns an error instead of the zero value on failure."},
		"slice":       {"slice list start end", "A sub-slice of list."},
		"mustSlice":   {"mustSlice list start end", "Like slice, but returns an error instead of the zero value on failure."},

		// Dicts
		"dict":               {"dict k1 v1 k2 v2 ...", "Builds a dict (map[string]any) from alternating keys/values."},
		"get":                {"get dict key", "The value of dict[key], or empty if absent."},
		"set":                {"set dict key value", "Sets dict[key]=value, returning dict."},
		"unset":              {"unset dict key", "Removes key from dict, returning dict."},
		"hasKey":             {"hasKey dict key", "Reports whether dict has key."},
		"pluck":              {"pluck key dict1 dict2 ...", "Collects the value of key from each dict into a list."},
		"merge":              {"merge dst src1 src2 ...", "Merges src dicts into dst (dst's existing keys win), returning dst."},
		"mustMerge":          {"mustMerge dst src1 src2 ...", "Like merge, but returns an error instead of the zero value on failure."},
		"mergeOverwrite":     {"mergeOverwrite dst src1 src2 ...", "Like merge, but src values overwrite dst's."},
		"mustMergeOverwrite": {"mustMergeOverwrite dst src1 src2 ...", "Like mergeOverwrite, but returns an error instead of the zero value on failure."},
		"values":             {"values dict", "A list of dict's values."},
		"keys":               {"keys dict1 dict2 ...", "A list of the (unsorted, deduplicated) keys across the given dicts."},
		"omit":               {"omit dict key ...", "A copy of dict without the given keys."},
		"dig":                {"dig key1 key2 ... default dict", "Looks up a nested key path in dict, returning default if any step is missing."},
		"deepCopy":           {"deepCopy value", "A deep copy of value."},
		"mustDeepCopy":       {"mustDeepCopy value", "Like deepCopy, but returns an error instead of the zero value on failure."},
		"deepEqual":          {"deepEqual a b", "Reports whether a and b are deeply equal (reflect.DeepEqual)."},

		// Flow control
		"tuple": {"tuple a b ...", "Builds a fixed-size list from its arguments (a lightweight anonymous struct)."},
		"dir":   {"dir path", "The directory portion of path (path.Dir)."},
		"base":  {"base path", "The final element of path (path.Base)."},
		"clean": {"clean path", "The shortest equivalent form of path (path.Clean)."},
		"isAbs": {"isAbs path", "Reports whether path is absolute (path.IsAbs)."},

		// OS path (filepath-backed variants of the above, for OS-native paths)
		"osBase":  {"osBase path", "The final element of path (filepath.Base)."},
		"osDir":   {"osDir path", "The directory portion of path (filepath.Dir)."},
		"osClean": {"osClean path", "The shortest equivalent form of path (filepath.Clean)."},
		"osExt":   {"osExt path", "The file extension of path (filepath.Ext) — shadowed by maelsink's own `ext`; see Docs()."},
		"osIsAbs": {"osIsAbs path", "Reports whether path is absolute (filepath.IsAbs)."},

		// Type conversion / reflection
		"atoi":       {"atoi s", "Parses s as an int."},
		"int":        {"int v", "Converts v to int."},
		"int64":      {"int64 v", "Converts v to int64."},
		"float64":    {"float64 v", "Converts v to float64."},
		"toDecimal":  {"toDecimal v", "Converts an octal string to its decimal int value."},
		"toString":   {"toString v", "Converts v to a string."},
		"toStrings":  {"toStrings list", "Converts every element of list to a string."},
		"kindOf":     {"kindOf v", "The reflect.Kind of v, as a string."},
		"kindIs":     {"kindIs kind v", "Reports whether v's reflect.Kind equals kind."},
		"typeOf":     {"typeOf v", "The Go type of v, as a string."},
		"typeIs":     {"typeIs typeName v", "Reports whether v's type equals typeName."},
		"typeIsLike": {"typeIsLike typeName v", "Like typeIs, allowing a leading \"*\" to match pointer types."},

		// JSON
		"toJson":           {"toJson v", "Marshals v to a compact JSON string."},
		"mustToJson":       {"mustToJson v", "Like toJson, but returns an error instead of the zero value on failure."},
		"toPrettyJson":     {"toPrettyJson v", "Marshals v to an indented JSON string."},
		"mustToPrettyJson": {"mustToPrettyJson v", "Like toPrettyJson, but returns an error instead of the zero value on failure."},
		"toRawJson":        {"toRawJson v", "Marshals v to JSON without HTML-escaping."},
		"mustToRawJson":    {"mustToRawJson v", "Like toRawJson, but returns an error instead of the zero value on failure."},
		"fromJson":         {"fromJson s", "Unmarshals a JSON string into a value."},
		"mustFromJson":     {"mustFromJson s", "Like fromJson, but returns an error instead of the zero value on failure."},

		// Regex
		"regexMatch":                 {"regexMatch pattern s", "Reports whether s matches the RE2 pattern."},
		"mustRegexMatch":             {"mustRegexMatch pattern s", "Like regexMatch, but returns an error instead of the zero value on an invalid pattern."},
		"regexFind":                  {"regexFind pattern s", "The first match of pattern in s."},
		"mustRegexFind":              {"mustRegexFind pattern s", "Like regexFind, but returns an error instead of the zero value on an invalid pattern."},
		"regexFindAll":               {"regexFindAll pattern s n", "All matches of pattern in s (up to n; -1 for all)."},
		"mustRegexFindAll":           {"mustRegexFindAll pattern s n", "Like regexFindAll, but returns an error instead of the zero value on an invalid pattern."},
		"regexReplaceAll":            {"regexReplaceAll pattern s repl", "Replaces every match of pattern in s with repl."},
		"mustRegexReplaceAll":        {"mustRegexReplaceAll pattern s repl", "Like regexReplaceAll, but returns an error instead of the zero value on an invalid pattern."},
		"regexReplaceAllLiteral":     {"regexReplaceAllLiteral pattern s repl", "Like regexReplaceAll, but repl is inserted literally (no $1-style expansion)."},
		"mustRegexReplaceAllLiteral": {"mustRegexReplaceAllLiteral pattern s repl", "Like regexReplaceAllLiteral, but returns an error instead of the zero value on an invalid pattern."},
		"regexSplit":                 {"regexSplit pattern s n", "Splits s on pattern (up to n substrings; -1 for all)."},
		"mustRegexSplit":             {"mustRegexSplit pattern s n", "Like regexSplit, but returns an error instead of the zero value on an invalid pattern."},
		"regexQuoteMeta":             {"regexQuoteMeta s", "Escapes RE2 metacharacters in s so it can be used as a literal pattern."},

		// Crypto / hash
		"sha1sum":                  {"sha1sum s", "Hex-encoded SHA-1 hash of s."},
		"sha256sum":                {"sha256sum s", "Hex-encoded SHA-256 hash of s."},
		"sha512sum":                {"sha512sum s", "Hex-encoded SHA-512 hash of s."},
		"adler32sum":               {"adler32sum s", "Adler-32 checksum of s, as a string."},
		"bcrypt":                   {"bcrypt s", "Bcrypt hash of s."},
		"htpasswd":                 {"htpasswd user pass", "An Apache htpasswd-format line for user/pass."},
		"derivePassword":           {"derivePassword counter type pass user domain", "A Master Password-algorithm-derived password."},
		"genPrivateKey":            {"genPrivateKey type", "Generates a PEM-encoded private key (\"rsa\", \"dsa\", or \"ecdsa\")."},
		"buildCustomCert":          {"buildCustomCert certPEM keyPEM", "Builds a tls.Certificate-like dict from PEM cert/key strings."},
		"genCA":                    {"genCA cn days", "Generates a self-signed CA certificate/key, valid for `days`."},
		"genCAWithKey":             {"genCAWithKey cn days privPEM", "Like genCA, using an existing private key."},
		"genSelfSignedCert":        {"genSelfSignedCert cn ips domains days", "Generates a self-signed certificate/key."},
		"genSelfSignedCertWithKey": {"genSelfSignedCertWithKey cn ips domains days privPEM", "Like genSelfSignedCert, using an existing private key."},
		"genSignedCert":            {"genSignedCert cn ips domains days ca", "Generates a certificate/key signed by the given CA."},
		"genSignedCertWithKey":     {"genSignedCertWithKey cn ips domains days privPEM ca", "Like genSignedCert, using an existing private key."},
		"encryptAES":               {"encryptAES key s", "AES-encrypts s with key, returning a base64 string."},
		"decryptAES":               {"decryptAES key s", "Decrypts a base64 string produced by encryptAES."},
		"uuidv4":                   {"uuidv4", "Random UUIDv4 (sprig's own — see also maelsink's `uuid`, the documented default identifier function)."},

		// Semver
		"semver":        {"semver s", "Parses s as a semantic version."},
		"semverCompare": {"semverCompare constraint s", "Reports whether s satisfies a semver constraint (e.g. \">=1.2.0\")."},

		// Env (removed by default — see §7.5.7's --template-unsafe-funcs)
		"env":           {"env name", "The value of environment variable `name`. Removed by default; restored only under --template-unsafe-funcs."},
		"expandenv":     {"expandenv s", "Expands $VAR references in s from the environment. Removed by default; restored only under --template-unsafe-funcs."},
		"getHostByName": {"getHostByName host", "Resolves host to an IP address (performs a DNS lookup). Removed by default; restored only under --template-unsafe-funcs."},

		// Flow / misc
		"seq":       {"seq start step end", "Generates a sequence of numbers as a space-separated string."},
		"until":     {"until count", "A list of ints [0, count)."},
		"untilStep": {"untilStep start stop step", "A list of ints from start to stop (exclusive), incrementing by step."},
		"all":       {"all arg ...", "Reports whether every argument is truthy (sprig's boolean AND)."},
		"any":       {"any arg ...", "Reports whether any argument is truthy (sprig's boolean OR)."},
		"urlParse":  {"urlParse url", "Parses url into a dict of its components (scheme, host, path, ...)."},
		"urlJoin":   {"urlJoin dict", "The inverse of urlParse: builds a URL string from a components dict."},
		"hello":     {"hello", "Returns the string \"Hello!\" — sprig's canonical smoke-test function."},
	}
}
